### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by jopereyral** [CodeDistillery/angular-no-captcha#10]
There is no language support, no? i can make a pull request for this feature. 

Greetings

**Comment by vepasto** [comment]
That would be great, thanks!

**Comment by kostonstyle** [comment]
That would be really awesome.

**Comment by jopereyral** [comment]
Sorry, guys.
I'm out of time these months

**Comment by nanuuki** [comment]
@jopereyral Any progress on this? :)
