### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by ryanblanks** [CodeDistillery/angular-no-captcha#12]
Can we get a version bump so we can pull the latest changes from bower?  I'm using the expire-callback in a project and would like to not have to manage working from my fork.

**Comment by Feijk** [comment]
Created a new release 0.4.0. Also adding the ability to test out examples on a local test server (Node.js). Documentation for the updates was added as well. Thanks for the request @ryanblanks

**Comment by Feijk** [comment]
Closing after bumping version.
