### ISSUE TITLE
Could not make it work in firefox!

### ISSUE THREAD

**Issue by mhmia** [CodeDistillery/angular-no-captcha#18]

**Comment by vepasto** [comment]
Have you already tested our demo page? http://codedistillery.github.io/angular-no-captcha/ It seems to work on my _Firefox 34.0.5_ (OSX Yosemite)

**Comment by mhmia** [comment]
Mine is 37.0.2,  37.0.1 works fine

**Comment by vepasto** [comment]
I just updated to version 37.0.2 on OSX Yosemite and [demo page](http://codedistillery.github.io/angular-no-captcha/) still works. Do you have any plugins (eg. adblockers) installed to firefox. If you have any plugins installed, please test with plugins disabled.

**Comment by nanuuki** [comment]
@mhmia Have you tried with the latest version (0.4.7)?
