### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by adribusc** [CodeDistillery/angular-no-captcha#22]
I have the following error after validation during the execution of the function removePLSContainers 

>ReferenceError: $document is not defined
>    at removePLSContainers (angular-no-captcha.js:61)
>    at angular-no-captcha.js:121
>    at n.$get.n.$broadcast (angular.js:14785)
>    at n.$get.n.$destroy (angular.js:14405)
>    at n.scopePrototype.$destroy (hint.js:1423)
>    at z (angular-route.js:907)
>    at angular-route.js:940
>    at angular.js:6995
>    at $get.h (angular.js:7135)
>    at k (angular.js:7795)

I solved it changing the directive

```javascript
  .directive('noCaptcha', [
    'noCAPTCHA',
    'googleGrecaptcha',
    '$document',
    function (noCaptcha, googleGrecaptcha, $document) {
```

**Comment by vepasto** [comment]
Thank you! 
Fixed in 0.4.4
