### ISSUE TITLE
Build is old. Need to rebuild the project.

### ISSUE THREAD

**Issue by tohidazizi** [CodeDistillery/angular-no-captcha#34]
The project has not been rebuilt since [1d1cd4 (Added support for stoken)](https://github.com/CodeDistillery/angular-no-captcha/commit/1d1cd4e55a1537e3e4178023b7e4f44a1f1cf4fa). So build\ [angular-no-captcha.min.js](https://github.com/CodeDistillery/angular-no-captcha/blob/master/build/angular-no-captcha.min.js) does not reflect changes in src\ [angular-no-captcha.js](https://github.com/CodeDistillery/angular-no-captcha/blob/master/src/angular-no-captcha.js).

**Comment by vepasto** [comment]
Fixed
