### ISSUE TITLE
Reset Captcha

### ISSUE THREAD

**Issue by hbtsmith** [CodeDistillery/angular-no-captcha#4]
Is there any way to reset captcha after the successful request?

**Comment by bastienmoulia** [comment]
Can you make an exemple of this please? I use `control="$scope.resetControl"`, but the resetControl variable has no function reset().

**Comment by arif-coer** [comment]
how to reset in controller ?

**Comment by vepasto** [comment]
@arif-coer live example at http://codedistillery.github.io/angular-no-captcha/  and source file https://github.com/CodeDistillery/angular-no-captcha/blob/gh-pages/index.html
