### ISSUE TITLE
Tried migrating from 0.2.0 to 0.3.0 and captcha is not working anymore

### ISSUE THREAD

**Issue by dkarter** [CodeDistillery/angular-no-captcha#6]
Am I missing any migration instructions?

```html
<no-captcha g-recaptcha-response="captchaResponse"></no-captcha>
```
and

```javascript
noCAPTCHAProvider.setSiteKey('[FILTERED]');
```

in config.

Not seeing anything in console (Chrome Dev Tools).

Thanks!

**Comment by vepasto** [comment]
In new version it downloads automatically googles api script. Have you removed it from your html imports?
