### ISSUE TITLE
no-captcha box can't be resized

### ISSUE THREAD

**Issue by Zeioth** [CodeDistillery/angular-no-captcha#8]
WORK: Original google-no-captcha resize using transform: scale.

    <div class="g-recaptcha" data-sitekey="mykey"  style="transform:scale(0.50);transform-origin:0 0")></div>

DON'T WORK: If you apply the same style to the no-captcha tag. It will ignore it.

    <no-captcha g-recaptcha-response="gRecaptchaResponse", theme='light', control="noCaptchaControl", site-key="mykey", style="transform:scale(0.50);transform-origin:0 0"></no-captcha>

**Comment by vepasto** [comment]
You can get it working by adding something like this to your css file:

no-captcha iframe {
  transform:scale(0.50);
  transform-origin:0 0;
}

**Comment by Zeioth** [comment]
It worked, thank you so much!
