### ISSUE TITLE
Is not working for IE8

### ISSUE THREAD

**Issue by mhmia** [CodeDistillery/angular-no-captcha#9]

**Comment by vepasto** [comment]
Have you tested to init no-captcha using attribute instead of element name:

```html 
<div no-captcha ...><div>
```

**Comment by mhmia** [comment]
<div no-captcha ...></div>, It worked, but the CSS is not supported in IE8 and display items got hidden, a custom css  is required to fix the IE8. Thank you very much.

**Comment by vepasto** [comment]
Glad you got it working!
